var res = {
    HelloWorld_png : "res/HelloWorld.png",
    CloseNormal_png : "res/CloseNormal.png",
    CloseSelected_png : "res/CloseSelected.png",
    btn_0_normal : "res/btn_0.png",
    btn_0_highlighted : "res/btn_0_hit.png",
    btn_1_normal : "res/btn_1.png",
    btn_1_highlighted : "res/btn_1_hit.png",
    btn_2_normal : "res/btn_2.png",
    btn_2_highlighted : "res/btn_2_hit.png",
    btn_3_normal : "res/btn_3.png",
    btn_3_highlighted : "res/btn_3_hit.png",
    btn_4_normal : "res/btn_4.png",
    btn_4_highlighted : "res/btn_4_hit.png",
    btn_5_normal : "res/btn_5.png",
    btn_5_highlighted : "res/btn_5_hit.png",
    btn_6_normal : "res/btn_6.png",
    btn_6_highlighted : "res/btn_6_hit.png",
    btn_7_normal : "res/btn_7.png",
    btn_7_highlighted : "res/btn_7_hit.png",
    btn_8_normal : "res/btn_8.png",
    btn_8_highlighted : "res/btn_8_hit.png",
    btn_9_normal : "res/btn_9.png",
    btn_9_highlighted : "res/btn_9_hit.png",
    btn_back_normal : "res/btn_back.png",
    btn_back_highlighted : "res/btn_back_hit.png",
    btn_enter_normal : "res/btn_enter.png",
    btn_enter_highlighted : "res/btn_enter_hit.png",
    btn_home_normal : "res/btn_home.png",
    btn_home_highlighted : "res/btn_home_hit.png",
    btn_usermn_normal : "res/btn_userMN.png",
    btn_usermn_highlighted : "res/btn_userMN_hit.png",
    btn_usersubmn_normal : "res/btn_userSubMN.png",
    btn_usersubmn_highlighted : "res/btn_userSubMN_hit.png",
    efc_5combo : "res/efc_5combo.png",
    efc_10combo : "res/efc_10combo.png",
    efc_combo : "res/efc_combo.png",
    efc_leveup_01 : "res/efc_leveup_01.png",
    efc_leveup_02 : "res/efc_leveup_02.png",
    efc_wrong_01 : "res/efc_wrong_01.png",
    efc_wrong_02 : "res/efc_wrong_02.png",
    image_answerboard_textbar : "res/image_answerboard_textbar.png",
    image_answerboard : "res/image_answerboard.png",
    image_bg : "res/image_bg.png",
    image_car : "res/image_car.png",
    image_combo_1 : "res/image_combo_1.png",
    image_combo_5 : "res/image_combo_5.png",
    image_combo_10 : "res/image_combo_10.png",
    image_combo_bg : "res/image_combo_bg.png",
    image_conTop_bg : "res/image_conTop_bg.png",
    image_conTop_coinbar : "res/image_conTop_coinbar.png",
    image_conTop_level : "res/image_conTop_level.png",
    image_levelguage_below : "res/image_levelguage_below.png",
    image_levelguage_bg : "res/image_levelguage_bg.png",
    image_levelguage_center : "res/image_levelguage_center.png",
    image_levelguage_top : "res/image_levelguage_top.png",
    image_o : "res/image_o.png",
    image_x : "res/image_x.png"
};

var g_resources = [
    //image
    res.HelloWorld_png,
    res.CloseNormal_png,
    res.CloseSelected_png,
    res.btn_0_normal,
    res.btn_0_highlighted,
    res.btn_1_normal,
    res.btn_1_highlighted,
    res.btn_2_normal,
    res.btn_2_highlighted,
    res.btn_3_normal,
    res.btn_3_highlighted,
    res.btn_4_normal,
    res.btn_4_highlighted,
    res.btn_5_normal,
    res.btn_5_highlighted,
    res.btn_6_normal,
    res.btn_6_highlighted,
    res.btn_7_normal,
    res.btn_7_highlighted,
    res.btn_8_normal,
    res.btn_8_highlighted,
    res.btn_9_normal,
    res.btn_9_highlighted,
    res.btn_back_normal,
    res.btn_back_highlighted,
    res.btn_enter_normal,
    res.btn_enter_highlighted,
    res.btn_home_normal,
    res.btn_home_highlighted,
    res.btn_usermn_normal,
    res.btn_usermn_highlighted,
    res.btn_usersubmn_normal,
    res.btn_usersubmn_highlighted,
    res.image_answerboard_textbar,
    res.image_answerboard,
    res.image_bg,
    res.image_car,
    res.image_combo_bg,
    res.image_levelguage_bg,
    res.image_o,
    res.image_x,
    res.image_conTop_bg

    //plist

    //fnt

    //tmx

    //bgm

    //effect
];